/*=================================================================
 *
 * matlabmpi - version 1.0
 *           - This program, including its separate functions,
 *             makes it possible for the MATLAB programmer to use
 *             MPI without calling MPI functions.
 *
 *             This program will always start a MATLAB function
 *             'matlabmain' with a verbosity parameter.
 *
 * Prerequisites:
 *           - MATLAB (with compiler)
 *           - MCR (MATLAB Compiler Runtime) environment
 *           - MPI
 *
 * 2012-11-08 - Jeroen Engelberts (SARA)
 *=================================================================*/

#include <stdio.h>
#include <mpi.h>
#include <unistd.h>
#include "matlabmpi.h"

/* Include the MCR header file and the library specific header file 
 * as generated by MATLAB Compiler */
#include "libmmpi.h"

/* MPI rank and size and verbosity declared globally, to be present in main and run_main */
int mpi_rank, mpi_size;
int mpibuffersize=1000000;
int verbosity=0;

int run_main(int argc, char **argv)
{
    mxArray *MLmpi_size, *MLmpi_rank, *MLbuffersize, *MLverbosity;

    /* Call the mclInitializeApplication routine. Make sure that the application
     * was initialized properly by checking the return status. This initialization
     * has to be done before calling any MATLAB API's or MATLAB Compiler generated
     * shared library functions.  */
    if( !mclInitializeApplication(NULL,0) )
    {
        fprintf(stderr, "Could not initialize the application.\n");
    	return -1;
    }
    
    /* Call the library intialization routine and make sure that the
     * library was initialized properly. */
    if (!libmmpiInitialize()){
        fprintf(stderr,"Could not initialize the library.\n");
        return -2;
    }
    else
    {
    /* Call the library function */
        double *buf;
        MLmpi_size = mxCreateDoubleMatrix(1,1,mxREAL);
        buf = mxGetPr(MLmpi_size);
        *buf = (double) mpi_size;
        MLmpi_rank = mxCreateDoubleMatrix(1,1,mxREAL);
        buf = mxGetPr(MLmpi_rank);
        *buf = (double) mpi_rank;
	MLbuffersize = mxCreateDoubleMatrix(1,1,mxREAL);
	buf = mxGetPr(MLbuffersize);
	*buf = (double) mpibuffersize;
	if (MM_BUFFER==NULL) {
		MM_BUFFER=malloc(mpibuffersize);
	}
        mlfSetmpistuff(MLmpi_size,MLmpi_rank,MLbuffersize);
        MLverbosity = mxCreateDoubleMatrix(1,1,mxREAL);
        buf = mxGetPr(MLverbosity);
        *buf = (double) verbosity;
        mlfMatlabmain(MLverbosity);
    }
    /* Free the memory created */
    mxDestroyArray(MLmpi_size); MLmpi_size=0;
    mxDestroyArray(MLmpi_rank); MLmpi_rank=0; 
     
    /* Call the library termination routine */
    libmmpiTerminate();

/* Note that you should call mclTerminate application at the end of
 * your application.
 */
    mclTerminateApplication();
    return 0;
}

int main(int argc, char *argv[])
{
    int rc;
    int ch;
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD,&mpi_rank);
    MPI_Comm_size(MPI_COMM_WORLD,&mpi_size);
    while ((ch = getopt(argc, argv, "hv:b:")) !=-1) {
        switch(ch) {
        case 'v':
            verbosity=atoi(optarg);
            if (mpi_rank==0) {
                printf("Setting verbosity to level %d.\n",verbosity);
            }
            break;
        case 'b':
            mpibuffersize=atoi(optarg);
            if (mpi_rank==0) {
                printf("Setting the buffer size to %d bytes.\n",mpibuffersize);
            }
            break;
        case 'h':
        case '?':
        default:
            if (mpi_rank==0) {
                printf("\nmatlabprog can be run without command line options.\n");
                printf("\nThese are the optional command line parameters:\n");
                printf("\t-b Sets the MPI buffer size (bytes).\n");
                printf("\t-h Prints this help message.\n");
                printf("\t-v Sets the verbosity level [0-3].\n\n");
            }
            MPI_Finalize();
            return 5;
        }
    }
    mclmcrInitialize();
    rc=mclRunMain((mclMainFcnType)run_main,0,NULL);
    free(MM_BUFFER);
    MPI_Finalize();
    return rc;
}
