function varargout = sodaVerifyFieldNames(conf,modeStr)

authorizedFieldNames =...
    {'assimilate',...
     'avgWalltimePerParSet',...
     'badScore',...
     'cBeta',...
     'convMaxDiff',...
     'convUseLastFraction',...
     'converged',...
     'covModelPert',...
     'covObsPert',...
     'crashAndBurn',...
     'critGelRubConvd',...
     'drawInterval',...
     'doPlot',...
     'evalCol',...
     'executeInParallel',...
     'initMethodKF',...
     'initValuesKF',...
     'initMethodNOKF',...
     'initValuesNOKF',...
     'isSingleObjective',...
     'isMultiObjective',...
     'jumpRate',...
     'kurt',...
     'llCols',...
     'modeGelRub',...
     'modeStr',...
     'modelName',...
     'namesNOKF',...
     'nCompl',...
     'nDASteps',...
     'nGelRub',...
     'nMembers',...
     'nModelEvalsMax',...
     'nOffspring',...
     'nOffspringFraction',...
     'nOffspringPerCompl',...
     'nOptPars',...
     'nNOKF',...
     'nObjs',...
     'nPrior',...
     'nSamples',...
     'nSamplesPerCompl',...
     'nStatesKF',...
     'nStatesNOKF',...
     'nWorkers',...
     'objCallStr',...
     'objCallStrs',...
     'objCol',...
     'obsState',...
     'obsStateTime',...
     'objTexName',...
     'objTexNames',...
     'omegaBeta',...
     'optEndTime',...
     'optStartTime',...
     'parCols',...
     'paretoCol',...
     'paretoMethod',...
     'parNames',...
     'parNamesTex',...
     'parSpaceHiBound',...
     'parSpaceLoBound',...
     'priorTimes',...
     'randSeed',...
     'realPartOnly',...
     'sampleDrawMode',...
     'saveEnKFResults',...
     'saveInterval',...
     'simTime',...
     'startFromUniform',...
     'stateNamesKF',...
     'stateSpaceHiBound',...
     'stateSpaceLoBound',...
     'useIniFile',...
     'thresholdL',...
     'verboseOutput',...
     'visualizationCall'};


switch modeStr
    case 'check'
        F = fieldnames(conf);
        for k=1:numel(F)
            if ~any(strcmp(F{k},authorizedFieldNames))
                error(['Unrecognized field ',char(39),F{k},char(39),...
                    ' in variable conf.'])
            end

        end
        varargout = {};
    case 'show'
        disp(sprintf('%s\n',authorizedFieldNames{:}))
        varargout = {};
    case 'return'
        varargout{1} = authorizedFieldNames;
end

